### ISSUE TITLE
TestArrayUtils - inconsistent results on different builds

### ISSUE THREAD

**Issue by dtaller** [LLNL/CARE#11]
The test TestArrayUtils.cpp:886 (code snippet below) gives different results on the rzansel debug vs relwithdebinfo builds. Perhaps there is a memory issue? We should investigate

  // change the cutoff
  // CURRENTLY TEST GIVES DIFFERENT RESULTS WHEN COMPILED RELEASE VS DEBUG!!!
  cutoff = 5.0;
  result = care_utils::PickAndPerformFindMinIndex<int>(a, nullptr, subsetrev, 7, threshold7, cutoff, threshIdx);

**Comment by adayton1** [comment]
Resolved with PR #85
