### ISSUE TITLE
Full code examples?

### ISSUE THREAD

**Issue by ian-bertolacci** [LLNL/CARE#2]
Are there any examples (other than BenchmarkNumeric, which is pretty bare) of using CARE?
It's possible that these are in the docs, but currently users have to download and build it themselves.

**Comment by robinson96** [comment]
Hey Ian, 
We're working on putting together better examples as I type this. (right @adayton1?). 
In the meantime, the best set of examples to check out is the unit tests. Documentation there isn't great, but you should be able to get some insight into the basics from them. 
Let us know if you have specific questions, happy to help out.

**Comment by ian-bertolacci** [comment]
Great! Looking forward to checking those out.

**Comment by adayton1** [comment]
Hi Ian,

Yes, we’ll add some example code soon.

- Alan
